### ISSUE TITLE
[Crash] Being killed by a Catalyst with Forgotten Graves will cause a crash.

### ISSUE THREAD

**Issue by SlayerTheChikken** [0x00002a/Soul-Shards-Despawn#6]
[crash-2023-11-01_12.05.53-server.txt](https://github.com/0x00002a/Soul-Shards-Despawn/files/13249954/crash-2023-11-01_12.05.53-server.txt)
[crash-2023-11-01_14.37.59-server.txt](https://github.com/0x00002a/Soul-Shards-Despawn/files/13249955/crash-2023-11-01_14.37.59-server.txt)
[latest.log](https://github.com/0x00002a/Soul-Shards-Despawn/files/13249956/latest.log)

The user who reported this says "Hitting a Warden in ancient city causes the server to crash." spawning in a warden and attacking it did not produce a crash nor did killing it in my game, however I was unable to find an ancient city, not sure if that has anything to do with it.

Looking at the report I guess there is no catch for a null value? i dunno

**Comment by SlayerTheChikken** [comment]
Could also be Lithium or Polymer..

**Comment by SlayerTheChikken** [comment]
Update: this happens when being killed near a catalyst with forgotten graves mod,
my guess is it spawns a grave so theres no xp to try to get leading to a null crash, ill try to fix soon

**Comment by SlayerTheChikken** [comment]
I made a "fix" which I won't make a pull request for obvious reasons, if someone else wants to make a better one have at it :p

https://github.com/TeamChikken/Soul-Shards-Despawn-CHKNFork-1.19.2/commit/5cd4a19e1e8fd95dcb09fb0487f603457faed64b

**Comment by SlayerTheChikken** [comment]
For google searches: 

```
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2945$class_2946.method_12794()" because the return value of "net.minecraft.class_2945.method_12783(net.minecraft.class_2940)" is null
	at net.minecraft.class_2945.method_12789(class_2945.java:119)
	at info.x2a.soulshards.core.EventHandler.shouldDropXp(EventHandler.java:85)
	at net.minecraft.class_1309.handler$gdj001$soulshards$shouldDropXp(class_1309.java:51195)
	at net.minecraft.class_1309.method_6054(class_1309.java:585)
	at net.minecraft.class_7132.method_32947(class_7132.java:57)
	at net.minecraft.class_3218.method_43663(class_3218.java:974)
	at net.minecraft.class_3218.method_32888(class_3218.java:954)
	at net.minecraft.class_1936.method_43275(class_1936.java:104)
	at net.minecraft.class_1297.method_32875(class_1297.java:1079)
	at net.minecraft.class_1297.method_32876(class_1297.java:1083)
	at net.minecraft.class_3222.method_6078(class_3222.java:589)
	at net.minecraft.class_1309.method_5643(class_1309.java:1204)
	at net.minecraft.class_1657.method_5643(class_1657.java:952)
	at net.minecraft.class_3222.method_5643(class_3222.java:713)
	at net.minecraft.class_1308.method_6121(class_1308.java:1429)
	at net.minecraft.class_7260.method_6121(class_7260.java:249)
	at net.minecraft.class_4816.method_24590(class_4816.java:50)
	at net.minecraft.class_4816.method_18920(class_4816.java:17)
	at net.minecraft.class_4097.method_18922(class_4097.java:49)
	at net.minecraft.class_4095.method_18891(class_4095.java:718)
	at net.minecraft.class_4095.method_19542(class_4095.java:475)
	at net.minecraft.class_7260.method_5958(class_7260.java:310)
	at net.minecraft.class_1308.method_6023(class_1308.java:770)
	at net.minecraft.class_1309.method_6007(class_1309.java:2641)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_7260.method_5773(class_7260.java:277)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
